<?php
declare(strict_types=1);
namespace App\Services;

use App\Core\Database;
use App\Security\TransportSecurity;
use Throwable;

final class ProductionSecurityValidator
{
    public static function evaluate(array $overrides=[],array $server=[],bool $runtime=true): array
    {
        $get=static fn(string$key,mixed$default=''):mixed=>array_key_exists($key,$overrides)?$overrides[$key]:env($key,$default);
        $bool=static fn(string$key,bool$default=false):bool=>filter_var($get($key,$default),FILTER_VALIDATE_BOOL,FILTER_NULL_ON_FAILURE)??$default;
        $checks=[];$add=static function(string$category,string$id,string$label,string$status,string$detail,bool$critical=true)use(&$checks):void{$checks[]=['category'=>$category,'id'=>$id,'label'=>$label,'status'=>$status,'detail'=>$detail,'critical'=>$critical];};
        $production=strtolower(trim((string)$get('APP_ENV','production')))==='production';
        $add('Application','app_env','Production environment selected',$production?'PASS':'FAIL',$production?'Production mode is selected.':'Set APP_ENV=production before deployment.');
        $debug=$bool('APP_DEBUG',false);$add('Application','debug','Verbose debugging disabled',!$debug?'PASS':'FAIL',!$debug?'Debug output is disabled.':'APP_DEBUG must be false for production.');
        $url=trim((string)$get('APP_URL',''));$validUrl=filter_var($url,FILTER_VALIDATE_URL)!==false;$httpsUrl=$validUrl&&strtolower((string)parse_url($url,PHP_URL_SCHEME))==='https';$add('Transport','app_url','Canonical HTTPS application URL',$httpsUrl?'PASS':'FAIL',$httpsUrl?'A valid HTTPS URL is configured.':'Configure a valid HTTPS APP_URL.');
        $enforce=$bool('HTTPS_ENFORCE',false);$add('Transport','https_enforce','HTTPS enforcement configured',$enforce?'PASS':'FAIL',$enforce?'Application HTTPS enforcement is enabled.':'Enable HTTPS_ENFORCE after HTTPS is verified.');
        if($server!==[]){$https=TransportSecurity::isHttps($server);$add('Transport','request_https','Current request uses HTTPS',$https?'PASS':'WARNING',$https?'Direct server HTTPS indication is present.':'Current request is not directly indicated as HTTPS.',false);}
        $secureCookie=$bool('SESSION_SECURE',false);$add('Session','secure_cookie','Secure session cookie configured',$secureCookie?'PASS':'FAIL',$secureCookie?'Secure cookies are required.':'Set SESSION_SECURE=true for production.');
        $sameSite=(string)$get('SESSION_SAMESITE','Lax');$add('Session','same_site','SameSite policy is valid',in_array($sameSite,['Lax','Strict'],true)?'PASS':'FAIL',in_array($sameSite,['Lax','Strict'],true)?'SameSite is compatible with CHIMERA.':'Use Lax or Strict.');
        $add('Session','http_only','HttpOnly and strict session mode','PASS','HttpOnly, strict mode, and cookie-only sessions are enforced in code.');
        $hashKey=(string)$get('TELEMETRY_HASH_KEY','');$add('Telemetry','hash_key','Telemetry hashing key configured',strlen($hashKey)>=32?'PASS':'FAIL',strlen($hashKey)>=32?'A sufficiently long hashing key is configured.':'Configure a random TELEMETRY_HASH_KEY of at least 32 characters.');
        foreach(['DB_HOST'=>'Database host','DB_PORT'=>'Database port','DB_DATABASE'=>'Database name','DB_USERNAME'=>'Runtime database user','DB_PASSWORD'=>'Runtime database password']as$key=>$label){$present=trim((string)$get($key,''))!=='';$add('Database',strtolower($key),$label,$present?'PASS':'FAIL',$present?'Configured.':'Missing.');}
        $dbUser=strtolower(trim((string)$get('DB_USERNAME','')));$notRoot=$dbUser!==''&&!in_array($dbUser,['root','admin','administrator'],true);$add('Database','least_privilege_user','Dedicated runtime database identity',$notRoot?'PASS':'FAIL',$notRoot?'Configured identity is not an administrative default.':'Use a dedicated non-root database account.');
        $storage=trim((string)$get('DOCUMENT_STORAGE_PATH',''));$storagePath=$storage!==''?$storage:BASE_PATH.'/storage/uploads/documents';$absolute=DocumentStorage::isAbsolutePath($storagePath);$storageMode=strtoupper(trim((string)$get('DEPLOYMENT_STORAGE_MODE',DocumentStorage::PRIVATE_OUTSIDE_WEBROOT)));$protectedMode=$storageMode===DocumentStorage::PROTECTED_IN_WEBROOT;
        if($protectedMode){$staticProtection=$absolute&&DocumentStorage::isProtectedInWebrootPath($storagePath,$storageMode);$add('Storage','private_storage','PROTECTED_IN_WEBROOT storage topology',$staticProtection?'PASS':'FAIL',$staticProtection?'Storage is restricted to the protected runtime path and static denial controls are present.':'Protected mode requires the exact storage/uploads/documents path and all static denial controls.');$denialVerified=$bool('WEBROOT_DENIAL_VERIFIED',false);$add('Storage','webroot_denial_live','Protected web-root HTTP denial',$denialVerified?'PASS':'FAIL',$denialVerified?'Operator recorded the required live 403/404 denial checks.':'PENDING LIVE VERIFICATION: keep deployment blocked until .env and private/storage paths return 403 or 404.');}
        else{$outside=$absolute&&!DocumentStorage::isInsidePublicRoot($storagePath,$storageMode);$add('Storage','private_storage','Document storage is absolute and non-public',$outside?'PASS':'FAIL',$outside?'Storage resolves outside the public root.':'Configure an absolute path outside public/.');}
        $max=filter_var($get('DOCUMENT_MAX_BYTES',''),FILTER_VALIDATE_INT,['options'=>['min_range'=>1,'max_range'=>52428800]]);$add('Upload','upload_limit','Upload limit is bounded',$max!==false?'PASS':'FAIL',$max!==false?'Upload size is within the allowed production bound.':'Set DOCUMENT_MAX_BYTES between 1 and 52428800.');
        $extensions=array_values(array_filter(array_map(static fn(string$v):string=>strtolower(trim($v)),explode(',',(string)$get('DOCUMENT_ALLOWED_EXTENSIONS','')))));$validExtensions=$extensions!==[]&&array_diff($extensions,['pdf','txt','csv','md'])===[];$add('Upload','extensions','Upload extension allowlist is constrained',$validExtensions?'PASS':'FAIL',$validExtensions?'Only supported non-executable document extensions are enabled.':'Use only pdf, txt, csv, and md.');
        $lab=$bool('VULNERABILITY_LAB_ENABLED',false);$add('Controlled Lab','lab_mode','Vulnerability lab mode',$lab?'WARNING':'PASS',$lab?'AUTHORIZED LAB MODE ENABLED: controlled vulnerabilities are exposed.':'SAFE NORMAL MODE: controlled lab is disabled.',!$lab);
        if($protectedMode){$envStatic=DocumentStorage::hasStaticWebDenialControls();$add('Environment','env_location','.env protected in web root',$envStatic?'PASS':'FAIL',$envStatic?'Root policy explicitly denies dotfiles; live verification remains separately required.':'Required root dotfile denial policy is missing.');}
        else{$envOutside=!str_starts_with(strtolower(str_replace('\\','/',BASE_PATH.'/.env')),strtolower(str_replace('\\','/',BASE_PATH.'/public/')));$add('Environment','env_location','.env is outside public root',$envOutside?'PASS':'FAIL',$envOutside?'Environment file is outside public/.':'Move the environment file outside the web root.');}
        if($runtime){
            foreach(['storage/logs','storage/sessions','storage/uploads']as$directory){$path=BASE_PATH.'/'.$directory;$ok=is_dir($path)&&is_writable($path);$add('Storage','writable_'.str_replace('/','_',$directory),$directory.' writable',$ok?'PASS':'FAIL',$ok?'Required runtime directory is writable.':'Create the directory with least necessary write permissions.');}
            try{$db=Database::connection();$row=$db->query('SELECT DATABASE() database_name,CURRENT_USER() runtime_user')->fetch();$tables=(int)$db->query("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name IN ('users','documents','user_activity','security_events','security_sessions','security_score_contributors','decoy_endpoints','honeytokens','honeytoken_events','vulnerability_modules','vulnerability_state_changes')")->fetchColumn();$safe=is_array($row)&&$tables===11&&!str_starts_with(strtolower((string)$row['runtime_user']),'root@');$add('Database','runtime_connection','Runtime database and schema',$safe?'PASS':'FAIL',$safe?'Dedicated connection and expected schema are available.':'Database connection, account, or schema is not deployment-ready.');}catch(Throwable){$add('Database','runtime_connection','Runtime database and schema','FAIL','Database readiness probe failed safely.');}
        }
        $failures=count(array_filter($checks,static fn(array$c):bool=>$c['status']==='FAIL'&&$c['critical']));$warnings=count(array_filter($checks,static fn(array$c):bool=>$c['status']==='WARNING'));
        $gate=$failures>0?'BLOCKED':($lab?'AUTHORIZED_LAB_MODE_READY_WITH_WARNING':($warnings>0?'NORMAL_MODE_READY_WITH_WARNING':'NORMAL_MODE_READY'));
        return['mode'=>$lab?'AUTHORIZED_LAB':'NORMAL_SAFE','gate'=>$gate,'status'=>$failures>0?'FAIL':($warnings>0||$lab?'WARNING':'PASS'),'summary'=>['pass'=>count(array_filter($checks,static fn(array$c):bool=>$c['status']==='PASS')),'warning'=>$warnings,'fail'=>count(array_filter($checks,static fn(array$c):bool=>$c['status']==='FAIL'))],'checks'=>$checks];
    }
}
