<?php
declare(strict_types=1);
$app=require dirname(__DIR__).'/bootstrap/app.php';
use App\Security\SecurityHeaders;use App\Security\TransportSecurity;use App\Security\UploadValidator;use App\Services\ProductionSecurityValidator;use App\Services\RepositorySecretScanner;
$p=0;$f=0;$check=function(bool$ok,string$label)use(&$p,&$f):void{echo($ok?'[PASS] ':'[FAIL] ').$label.PHP_EOL;$ok?$p++:$f++;};$root=dirname(__DIR__);
$base=['APP_ENV'=>'production','APP_DEBUG'=>'false','APP_URL'=>'https://chimera.example','HTTPS_ENFORCE'=>'true','SESSION_SECURE'=>'true','SESSION_SAMESITE'=>'Lax','TELEMETRY_HASH_KEY'=>str_repeat('k',32),'DB_HOST'=>'db.internal','DB_PORT'=>'3306','DB_DATABASE'=>'chimera','DB_USERNAME'=>'chimera_app','DB_PASSWORD'=>'unit-only-placeholder','DOCUMENT_STORAGE_PATH'=>$root.'/storage/uploads/documents','DOCUMENT_MAX_BYTES'=>'5242880','DOCUMENT_ALLOWED_EXTENSIONS'=>'pdf,txt,csv,md','VULNERABILITY_LAB_ENABLED'=>'false'];
$ready=ProductionSecurityValidator::evaluate($base,[],false);$check($ready['status']==='PASS'&&$ready['gate']==='NORMAL_MODE_READY','Valid production normal mode passes deterministic gate');
$debug=ProductionSecurityValidator::evaluate([...$base,'APP_DEBUG'=>'true'],[],false);$check($debug['status']==='FAIL','Production with debug enabled fails');
$missing=ProductionSecurityValidator::evaluate([...$base,'TELEMETRY_HASH_KEY'=>''],[],false);$check($missing['status']==='FAIL','Missing required telemetry secret fails');
$badUrl=ProductionSecurityValidator::evaluate([...$base,'APP_URL'=>'http://not-production.example'],[],false);$check($badUrl['status']==='FAIL','Non-HTTPS production APP_URL fails');
$rootDb=ProductionSecurityValidator::evaluate([...$base,'DB_USERNAME'=>'root'],[],false);$check($rootDb['status']==='FAIL','Administrative database username fails');
$lab=ProductionSecurityValidator::evaluate([...$base,'VULNERABILITY_LAB_ENABLED'=>'true'],[],false);$check($lab['status']==='WARNING'&&$lab['gate']==='AUTHORIZED_LAB_MODE_READY_WITH_WARNING','Authorized lab mode is explicit and warning-gated');
$serialized=json_encode($ready,JSON_THROW_ON_ERROR);$check(!str_contains($serialized,'unit-only-placeholder')&&!str_contains($serialized,str_repeat('k',32)),'Validator output never exposes secret values');
$check(TransportSecurity::isHttps(['HTTPS'=>'on']),'Direct HTTPS server indication is accepted');
$check(TransportSecurity::isHttps(['REQUEST_SCHEME'=>'https']),'Direct HTTPS request scheme is accepted');
$check(!TransportSecurity::isHttps(['HTTP_X_FORWARDED_PROTO'=>'https']),'Untrusted forwarded HTTPS header is ignored');
$check(!TransportSecurity::isHttps(['HTTPS'=>'malformed','HTTP_X_FORWARDED_PROTO'=>'https']),'Malformed HTTPS and forwarded headers fail safely');
$oldEnv=getenv('APP_ENV');putenv('APP_ENV=production');$httpsHeaders=SecurityHeaders::policy(['HTTPS'=>'on']);$httpHeaders=SecurityHeaders::policy(['HTTPS'=>'off']);if($oldEnv===false)putenv('APP_ENV');else putenv('APP_ENV='.$oldEnv);
$check(isset($httpsHeaders['Strict-Transport-Security']),'HSTS is emitted only for production HTTPS');
$check(!isset($httpHeaders['Strict-Transport-Security']),'HSTS is omitted for production HTTP');
$check(($httpsHeaders['X-Content-Type-Options']??'')==='nosniff'&&str_contains($httpsHeaders['Content-Security-Policy'],'frame-ancestors'), 'CSP, frame protection, and nosniff are present');
$check(($httpsHeaders['Cache-Control']??'')==='no-store, private, max-age=0','Dynamic sensitive responses receive no-store cache policy');
$routes=file_get_contents($root.'/routes/web.php');preg_match_all('/\$router->post\([^\n]+/',$routes,$posts);$check($posts[0]!==[]&&array_reduce($posts[0],static fn(bool$ok,string$line):bool=>$ok&&str_contains($line,'VerifyCsrf'),true),'Every state-changing POST route uses CSRF middleware');
$check(!preg_match('/\$router->get\([^\n]*,\s*\'(?:changeState|delete|upload|update|logout|register|login)\'\]/',$routes),'GET routes do not invoke mutation handlers');
$check(substr_count($routes,"'/security/deployment-readiness'")===1&&preg_match("#/security/deployment-readiness'.*RequireRole\(\['security_admin'\]\)#",$routes)===1,'Readiness page is uniquely Security Admin protected');
foreach(['/lab','/lab/robots.txt','/lab/sqli','/lab/idor','/lab/xss']as$route)$check(preg_match('#'.preg_quote($route,'#')."'.*RequireLabEnabled#",$routes)===1,'Lab gate protects '.$route);
$application=file_get_contents($root.'/app/Core/Application.php');$bootstrap=file_get_contents($root.'/bootstrap/app.php');$check(str_contains($application,"APP_ENV', 'production')) !== 'production'")&&str_contains($bootstrap,'!$production && env_bool'),'Production debug disclosure is suppressed in bootstrap and dispatcher');
$index=file_get_contents($root.'/public/index.php');$check(str_contains($index,'SERVER_ERROR')&&!str_contains($index,'getMessage()'),'Bootstrap failure response is generic and does not echo exceptions');
$router=file_get_contents($root.'/app/Core/Router.php');$check(str_contains($router,'METHOD_NOT_ALLOWED')&&str_contains($router,"header('Allow:"),'Router returns explicit safe 405 responses');
$check(str_contains(file_get_contents($root.'/public/.htaccess'),'Options -Indexes')&&str_contains(file_get_contents($root.'/storage/.htaccess'),'Require all denied'),'Apache rules disable listing and deny storage access');
$check(str_contains(file_get_contents($root.'/storage/uploads/.htaccess'),'phtml|phar'),'Upload Apache rules deny executable extensions');
$tmp=tempnam(sys_get_temp_dir(),'chm-p9-');file_put_contents($tmp,'harmless text');$double=UploadValidator::validate(['error'=>UPLOAD_ERR_OK,'tmp_name'=>$tmp,'size'=>filesize($tmp),'name'=>'report.php.txt'],1024,['txt']);$reserved=UploadValidator::validate(['error'=>UPLOAD_ERR_OK,'tmp_name'=>$tmp,'size'=>filesize($tmp),'name'=>'CON.txt'],1024,['txt']);$null=UploadValidator::safeOriginalName("../safe\0.txt");unlink($tmp);
$check($double['errors']!==[],'Executable double-extension upload name is rejected');$check($reserved['errors']!==[],'Reserved platform filename is rejected');$check($null==='safe.txt','Null-byte-style and traversal filename is normalized safely');
$session=file_get_contents($root.'/app/Core/Session.php');$check(str_contains($session,"'httponly' => true")&&str_contains($session,"session.use_strict_mode")&&str_contains($session,"session.use_only_cookies"),'Session cookies enforce HttpOnly, strict mode, and cookie-only transport');
$auth=file_get_contents($root.'/app/Security/Auth.php');$check(substr_count($auth,'Session::regenerate()')>=2&&str_contains($auth,'Session::invalidate()'),'Authentication regenerates and logout invalidates the session');
$check(!preg_match('/(?:next|return|redirect|redirect_to|continue).*\$request->(?:input|query)/i',implode("\n",array_map('file_get_contents',glob($root.'/app/Controllers/*.php')))),'No request-controlled open redirect destination exists');
$check(RepositorySecretScanner::scan($root)===[],'Scoped repository secret scan finds no high-confidence secret material');
$analytics=file_get_contents($root.'/app/Services/SecurityAnalyticsService.php');$check(!preg_match('/\b(INSERT|UPDATE|DELETE|DROP|ALTER|TRUNCATE)\b/',$analytics)&&str_contains($analytics,'MAX_EXPORT = 1000'),'Analytics remains read-only and bounded');
$labService=file_get_contents($root.'/app/Lab/ControlledLabService.php');$check(!preg_match('/\b(shell_exec|system|exec|passthru|curl_exec|file_put_contents)\s*\(/',$labService),'Controlled lab contains no command, network, or file-write primitive');
$xss=file_get_contents($root.'/app/Lab/LabResponse.php');$check(str_contains($xss,'sandbox allow-scripts')&&str_contains($xss,"connect-src 'none'")&&!str_contains($xss,'allow-same-origin'),'XSS lab retains opaque-origin network-disabled sandbox');
echo"\n{$p} checks passed, {$f} failed.\n";exit($f===0?0:1);
