<?php
declare(strict_types=1);
$root=dirname(__DIR__);require $root.'/app/Core/Env.php';App\Core\Env::load($root.'/.env');
if((string)getenv('TEST_DB_DATABASE')!=='chimera_test'){echo"[FAIL] TEST_DB_DATABASE must be exactly chimera_test.\n";exit(1);}$testUser=(string)getenv('TEST_DB_USERNAME');$testPassword=(string)getenv('TEST_DB_PASSWORD');putenv('DB_DATABASE=chimera_test');$_ENV['DB_DATABASE']='chimera_test';putenv('DB_USERNAME='.$testUser);$_ENV['DB_USERNAME']=$testUser;putenv('DB_PASSWORD='.$testPassword);$_ENV['DB_PASSWORD']=$testPassword;require $root.'/bootstrap/app.php';
use App\Core\Database;use App\Core\Request;use App\Services\SecurityEventService;use App\Services\SecuritySessionService;
$db=Database::connection();$meta=$db->query('SELECT DATABASE() db,@@port port,CURRENT_USER() usr')->fetch();if($meta['db']!=='chimera_test'||(int)$meta['port']!==3308||!str_starts_with($meta['usr'],'chimera_test_app@')){echo"[FAIL] Unsafe Phase 5 integration target.\n";exit(1);} $startEvent=(int)$db->query('SELECT COALESCE(MAX(id),0) FROM security_events')->fetchColumn();$startSession=(int)$db->query('SELECT COALESCE(MAX(id),0) FROM security_sessions')->fetchColumn();
$stmt=$db->prepare('INSERT INTO users(name,email,password_hash,role,is_active) VALUES(?,?,?,?,1)');$email='phase5-'.bin2hex(random_bytes(5)).'@test.chimera';$stmt->execute(['Phase Five Actor',$email,password_hash('Synthetic!2026',PASSWORD_DEFAULT),'user']);$actor=(int)$db->lastInsertId();$p=0;$f=0;$check=static function(bool $ok,string $label)use(&$p,&$f):void{echo($ok?'[PASS] ':'[FAIL] ').$label."\n";$ok?$p++:$f++;};
$request=static fn(string $ip):Request=>new Request('GET','/phase5-test',[],[],['REMOTE_ADDR'=>$ip,'HTTP_USER_AGENT'=>'CHIMERA Phase5 Test'],[]);
try{
$e1=SecurityEventService::record($request('192.0.2.10'),'LOGIN_FAILURE');$row=$db->query("SELECT security_session_id FROM security_events WHERE id={$e1}")->fetch();$s1=(int)$row['security_session_id'];
$check($s1>0,'Relevant event creates a security session');$check((int)$db->query("SELECT threat_score FROM security_sessions WHERE id={$s1}")->fetchColumn()===5,'Documented login-failure weight is applied');
SecuritySessionService::correlate($e1);$check((int)$db->query("SELECT COUNT(*) FROM security_score_contributors WHERE security_session_id={$s1}")->fetchColumn()===1,'Reprocessing the same event is idempotent');
$e2=SecurityEventService::record($request('192.0.2.10'),'LOGIN_FAILURE');$check((int)$db->query("SELECT security_session_id FROM security_events WHERE id={$e2}")->fetchColumn()===$s1,'Same source and actor boundary correlate within the window');
$e3=SecurityEventService::record($request('192.0.2.11'),'LOGIN_FAILURE');$s2=(int)$db->query("SELECT security_session_id FROM security_events WHERE id={$e3}")->fetchColumn();$check($s2!==$s1,'Different sources do not merge');
$e4=SecurityEventService::record($request('192.0.2.10'),'ROLE_ACCESS_DENIED',$actor);$sActor=(int)$db->query("SELECT security_session_id FROM security_events WHERE id={$e4}")->fetchColumn();$check($sActor!==$s1,'Authenticated actor boundary does not merge with anonymous source session');
$db->exec("UPDATE security_sessions SET last_seen_at=DATE_SUB(CURRENT_TIMESTAMP,INTERVAL 31 MINUTE) WHERE id={$s1}");$e5=SecurityEventService::record($request('192.0.2.10'),'ACCESS_DENIED');$sNew=(int)$db->query("SELECT security_session_id FROM security_events WHERE id={$e5}")->fetchColumn();$check($sNew!==$s1,'Expired session causes a new session');
$benign=SecurityEventService::record($request('192.0.2.12'),'LOGIN_SUCCESS',$actor);$benignSession=(int)$db->query("SELECT security_session_id FROM security_events WHERE id={$benign}")->fetchColumn();$check((int)$db->query("SELECT threat_score FROM security_sessions WHERE id={$benignSession}")->fetchColumn()===0,'Benign event correlates without increasing score');
for($i=0;$i<3;$i++)SecurityEventService::record($request('192.0.2.20'),'HONEYTOKEN_TRIGGERED');$bounded=$db->query("SELECT id,threat_score,classification FROM security_sessions WHERE source_hash=(SELECT source_safe_identifier FROM security_events WHERE id>{$startEvent} AND endpoint='/phase5-test' ORDER BY id DESC LIMIT 1) AND user_id IS NULL ORDER BY id DESC LIMIT 1")->fetch();$sum=(int)$db->query("SELECT COALESCE(SUM(risk_delta),0) FROM security_score_contributors WHERE security_session_id=".(int)$bounded['id'])->fetchColumn();$check((int)$bounded['threat_score']===100&&$bounded['classification']==='CRITICAL','Repeated high-confidence signals are bounded at 100 and classified CRITICAL');$check(min(100,$sum)===(int)$bounded['threat_score'],'Current score is reconstructible from contributors with documented bounding');
$labels=(string)$db->query("SELECT GROUP_CONCAT(label) FROM security_score_contributors WHERE security_session_id={$s1}")->fetchColumn();$check(str_contains($labels,'Event #')&&str_contains($labels,'Failed authentication'),'Contributor evidence identifies event and rationale');
echo"\n{$p} Phase 5 integration checks passed, {$f} failed.\n";
}finally{$db->exec("DELETE FROM security_events WHERE id>{$startEvent}");$db->exec("DELETE FROM security_sessions WHERE id>{$startSession}");$del=$db->prepare('DELETE FROM users WHERE id=?');$del->execute([$actor]);}exit($f===0?0:1);
