<?php

declare(strict_types=1);

$root=dirname(__DIR__);require $root.'/app/Core/Env.php';App\Core\Env::load($root.'/.env');
if((string)getenv('TEST_DB_DATABASE')!=='chimera_test'){echo"[FAIL] TEST_DB_DATABASE must be exactly chimera_test.\n";exit(1);}$testUser=(string)getenv('TEST_DB_USERNAME');$testPassword=(string)getenv('TEST_DB_PASSWORD');putenv('DB_DATABASE=chimera_test');$_ENV['DB_DATABASE']='chimera_test';putenv('DB_USERNAME='.$testUser);$_ENV['DB_USERNAME']=$testUser;putenv('DB_PASSWORD='.$testPassword);$_ENV['DB_PASSWORD']=$testPassword;require $root.'/bootstrap/app.php';
use App\Core\Database;use App\Core\Request;use App\Lab\ControlledLabService;use App\Models\VulnerabilityModule;use App\Services\AdaptiveDeceptionService;use App\Services\SecurityEventService;
$db=Database::connection();$meta=$db->query('SELECT DATABASE() db,@@port port,CURRENT_USER() usr')->fetch();if($meta['db']!=='chimera_test'||(int)$meta['port']!==3308||!str_starts_with($meta['usr'],'chimera_test_app@')){echo"[FAIL] Unsafe Phase 7 integration target.\n";exit(1);}
$eventStart=(int)$db->query('SELECT COALESCE(MAX(id),0) FROM security_events')->fetchColumn();$sessionStart=(int)$db->query('SELECT COALESCE(MAX(id),0) FROM security_sessions')->fetchColumn();$userStart=(int)$db->query('SELECT COALESCE(MAX(id),0) FROM users')->fetchColumn();$moduleStart=(int)$db->query('SELECT COALESCE(MAX(id),0) FROM vulnerability_modules')->fetchColumn();$usersBefore=(int)$db->query('SELECT COUNT(*) FROM users')->fetchColumn();$docsBefore=(int)$db->query('SELECT COUNT(*) FROM documents')->fetchColumn();$activityBefore=(int)$db->query('SELECT COUNT(*) FROM user_activity')->fetchColumn();
$p=0;$f=0;$check=static function(bool $ok,string $label)use(&$p,&$f):void{echo($ok?'[PASS] ':'[FAIL] ').$label."\n";$ok?$p++:$f++;};
$request=new Request('GET','/lab/sqli',[],[],['REMOTE_ADDR'=>'192.0.2.70','HTTP_USER_AGENT'=>'CHIMERA Phase7 Test'],[]);
try{
$insert=$db->prepare('INSERT INTO vulnerability_modules(vulnerability_identifier,name,description,affected_component,expected_attack_surface,learning_objective,expected_impact,mitigation,state,is_active) VALUES(?,?,?,?,?,?,?,?,?,1)');
$fixtures=[['CHIM-VULN-001','IDOR','Synthetic only','/lab/idor','Synthetic objects','Ownership comparison','Synthetic exposure','Owner check','VULNERABLE'],['CHIM-VULN-002','SQLi','Synthetic only','/lab/sqli','Derived records','Binding comparison','Synthetic rows','Prepared statement','VULNERABLE'],['CHIM-VULN-003','XSS','Synthetic only','/lab/xss','Sandbox reflection','Encoding comparison','Sandbox script','HTML encoding','VULNERABLE']];foreach($fixtures as $row)$insert->execute($row);
$user=$db->prepare('INSERT INTO users(name,email,password_hash,role,is_active) VALUES(?,?,?,?,1)');$user->execute(['Phase Seven Operator','phase7-'.bin2hex(random_bytes(5)).'@test.chimera',password_hash('Synthetic!2026',PASSWORD_DEFAULT),'security_admin']);$actor=(int)$db->lastInsertId();
$check(count(ControlledLabService::sqlSearch('ARC-001','VULNERABLE'))===1,'Vulnerable SQL lab returns one exact synthetic record');
$check(count(ControlledLabService::sqlSearch("' OR '1'='1",'VULNERABLE'))===3,'Vulnerable SQL lab demonstrates bounded predicate bypass');
$check(ControlledLabService::sqlSearch("' UNION SELECT password FROM users",'VULNERABLE')===[]&&ControlledLabService::sqlSearch("ARC-001'; DROP TABLE users; --",'VULNERABLE')===[],'SQL lab rejects cross-table, stacked, and destructive syntax');
$check(ControlledLabService::sqlSearch("' OR '1'='1",'REMEDIATED')===[]&&count(ControlledLabService::sqlSearch('ARC-001','REMEDIATED'))===1,'Remediated SQL lab prevents the same bypass with binding');
$cross=ControlledLabService::idorLookup('analyst-a','LAB-2001','VULNERABLE');$check(($cross['owner']??null)==='analyst-b','Vulnerable IDOR returns another synthetic identity object');
$check(ControlledLabService::idorLookup('analyst-a','1','VULNERABLE')===null&&ControlledLabService::idorLookup('analyst-a','LAB-2001','REMEDIATED')===null,'IDOR rejects real-style IDs and remediated cross-owner access');
$check((ControlledLabService::idorLookup('analyst-a','LAB-1001','REMEDIATED')['owner']??null)==='analyst-a','Remediated IDOR permits the synthetic owner');
$payload='<script>document.body.dataset.lab="ok"</script>';$reflection=ControlledLabService::reflectedInput($payload);$check($reflection===$payload&&e($reflection)!==$reflection,'XSS lab preserves bounded input while remediated encoding neutralizes it');
$moduleId=(int)$db->query("SELECT id FROM vulnerability_modules WHERE vulnerability_identifier='CHIM-VULN-002'")->fetchColumn();$change=VulnerabilityModule::changeState($moduleId,'REMEDIATED',$actor,'Phase 7 integration countermeasure.');$check($change['changed']&&$change['from_state']==='VULNERABLE'&&$change['to_state']==='REMEDIATED','Allowlisted transaction records vulnerable-to-remediated state change');
$check((int)$db->query("SELECT COUNT(*) FROM vulnerability_state_changes WHERE vulnerability_module_id={$moduleId}")->fetchColumn()===1,'Module state history persists the countermeasure audit');
for($i=0;$i<4;$i++)SecurityEventService::record($request,'LOGIN_FAILURE');$before=AdaptiveDeceptionService::select($request,null);$labEvent=SecurityEventService::record($request,'LAB_VULNERABILITY_INTERACTION',null,['target_type'=>'lab_module','target_identifier'=>'CHIM-VULN-002','metadata'=>['module_identifier'=>'CHIM-VULN-002','module_state'=>'VULNERABLE','lab_authorized'=>true]]);$after=AdaptiveDeceptionService::select($request,null);$labRow=$db->query("SELECT security_session_id,risk_delta,metadata_json FROM security_events WHERE id={$labEvent}")->fetch();$check($labRow['security_session_id']===null&&(int)$labRow['risk_delta']===0,'Lab telemetry is stored with zero delta outside operational security sessions');
$check($before['score']===$after['score']&&$before['profile']['name']===$after['profile']['name'],'Lab activity cannot change normal score or adaptive profile');
$metadata=(string)$labRow['metadata_json'];$check(!preg_match('/password|cookie|authorization|session_identifier|DB_PASSWORD|CHM_HONEY_/i',$metadata),'Lab telemetry excludes secrets and token material');
$check((int)$db->query('SELECT COUNT(*) FROM users')->fetchColumn()===$usersBefore+1&&(int)$db->query('SELECT COUNT(*) FROM documents')->fetchColumn()===$docsBefore&&(int)$db->query('SELECT COUNT(*) FROM user_activity')->fetchColumn()===$activityBefore,'Lab operations leave real documents and product activity untouched');
echo"\n{$p} Phase 7 integration checks passed, {$f} failed.\n";
}finally{$db->exec("DELETE FROM security_events WHERE id>{$eventStart}");$db->exec("DELETE FROM security_sessions WHERE id>{$sessionStart}");$db->exec("DELETE FROM users WHERE id>{$userStart}");$db->exec("DELETE FROM vulnerability_modules WHERE id>{$moduleStart}");}exit($f===0?0:1);
