<?php

declare(strict_types=1);

use App\Core\Env;

$root=dirname(__DIR__);require $root.'/app/Core/Env.php';Env::load($root.'/.env');
if((string)getenv('TEST_DB_DATABASE')!=='chimera_test'||(string)getenv('DB_DATABASE')!=='chimera'||(string)getenv('DB_PORT')!=='3308'){echo"[FAIL] Phase 7 HTTP database guards failed.\n";exit(1);}
$testUser=(string)getenv('TEST_DB_USERNAME');$testPassword=(string)getenv('TEST_DB_PASSWORD');if($testUser===''||$testPassword===''){echo"[FAIL] Dedicated test credentials are required.\n";exit(1);}
$pdo=new PDO('mysql:host=127.0.0.1;port=3308;dbname=chimera_test;charset=utf8mb4',$testUser,$testPassword,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);$connection=$pdo->query('SELECT DATABASE() db,@@port port,CURRENT_USER() usr')->fetch();if($connection['db']!=='chimera_test'||(int)$connection['port']!==3308||!str_starts_with($connection['usr'],'chimera_test_app@')){echo"[FAIL] Unsafe Phase 7 HTTP target.\n";exit(1);}
$eventStart=(int)$pdo->query('SELECT COALESCE(MAX(id),0) FROM security_events')->fetchColumn();$sessionStart=(int)$pdo->query('SELECT COALESCE(MAX(id),0) FROM security_sessions')->fetchColumn();$userStart=(int)$pdo->query('SELECT COALESCE(MAX(id),0) FROM users')->fetchColumn();$moduleStart=(int)$pdo->query('SELECT COALESCE(MAX(id),0) FROM vulnerability_modules')->fetchColumn();
$passes=0;$failures=0;$check=static function(bool $ok,string $label)use(&$passes,&$failures):void{echo($ok?'[PASS] ':'[FAIL] ').$label."\n";$ok?$passes++:$failures++;};$servers=[];$clients=[];
function p7Client():CurlHandle{$c=curl_init();curl_setopt($c,CURLOPT_COOKIEFILE,'');curl_setopt($c,CURLOPT_RETURNTRANSFER,true);curl_setopt($c,CURLOPT_HEADER,true);curl_setopt($c,CURLOPT_FOLLOWLOCATION,false);curl_setopt($c,CURLOPT_TIMEOUT,10);return $c;}
function p7Request(CurlHandle $c,string $base,string $method,string $path,?array $fields=null):array{curl_setopt($c,CURLOPT_URL,$base.$path);curl_setopt($c,CURLOPT_CUSTOMREQUEST,$method);if($method==='GET'){curl_setopt($c,CURLOPT_HTTPGET,true);curl_setopt($c,CURLOPT_POSTFIELDS,null);}else{curl_setopt($c,CURLOPT_POST,true);curl_setopt($c,CURLOPT_POSTFIELDS,http_build_query($fields??[]));}$raw=curl_exec($c);if(!is_string($raw))throw new RuntimeException(curl_error($c));$size=curl_getinfo($c,CURLINFO_HEADER_SIZE);$head=substr($raw,0,$size);$headers=[];foreach(preg_split('/\r\n|\n|\r/',trim($head))as $line)if(str_contains($line,':')){[$k,$v]=explode(':',$line,2);$headers[strtolower(trim($k))]=trim($v);}return['status'=>(int)curl_getinfo($c,CURLINFO_RESPONSE_CODE),'headers'=>$headers,'body'=>substr($raw,$size)];}
function p7Csrf(string $html):string{if(!preg_match('/name="_token"\s+value="([^"]+)"/',$html,$m))throw new RuntimeException('CSRF token missing.');return html_entity_decode($m[1],ENT_QUOTES|ENT_HTML5,'UTF-8');}
function p7Start(string $root,bool $enabled,array &$servers):array{$socket=stream_socket_server('tcp://127.0.0.1:0',$errno,$error);if(!is_resource($socket))throw new RuntimeException('Port allocation failed.');$name=stream_socket_get_name($socket,false);fclose($socket);$port=(int)substr(strrchr((string)$name,':'),1);$base='http://127.0.0.1:'.$port;$env=getenv();$env['CHIMERA_E2E_BASE_URL']=$base;$env['CHIMERA_E2E_STORAGE']=$root.'/storage/uploads/e2e-documents';$env['VULNERABILITY_LAB_ENABLED']=$enabled?'true':'false';$log=$root.'/storage/logs/phase7-e2e-server.log';$process=proc_open([PHP_BINARY,'-S','127.0.0.1:'.$port,'-t',$root.'/public',$root.'/tests/e2e_server_router.php'],[0=>['pipe','r'],1=>['file',$log,'a'],2=>['file',$log,'a']],$pipes,$root,$env);if(!is_resource($process))throw new RuntimeException('Server start failed.');fclose($pipes[0]);$servers[]=$process;for($i=0;$i<30;$i++){try{$probe=p7Client();$ready=p7Request($probe,$base,'GET','/')['status']===200;curl_close($probe);if($ready)return[$base,$process];}catch(Throwable){}usleep(100000);}throw new RuntimeException('Server readiness failed.');}
function p7Stop($process):void{if(is_resource($process)){proc_terminate($process);proc_close($process);}}
function p7Login(CurlHandle $client,string $base,string $email,string $password):array{$page=p7Request($client,$base,'GET','/login');return p7Request($client,$base,'POST','/login',['_token'=>p7Csrf($page['body']),'email'=>$email,'password'=>$password]);}
try{
if((int)$pdo->query('SELECT COUNT(*) FROM vulnerability_modules')->fetchColumn()!==0)throw new RuntimeException('Phase 7 HTTP requires an unseeded vulnerability registry in chimera_test.');
$insert=$pdo->prepare('INSERT INTO vulnerability_modules(vulnerability_identifier,name,description,affected_component,expected_attack_surface,learning_objective,expected_impact,mitigation,state,is_active) VALUES(?,?,?,?,?,?,?,?,?,1)');$fixtures=[['CHIM-VULN-001','IDOR','Synthetic object lookup','/lab/idor','Synthetic objects','Ownership','Synthetic exposure','Owner check','VULNERABLE'],['CHIM-VULN-002','SQLi','Synthetic derived query','/lab/sqli','Bounded query','Prepared binding','Synthetic rows','Prepared statement','VULNERABLE'],['CHIM-VULN-003','XSS','Sandbox reflection','/lab/xss','Sandbox input','Encoding','Sandbox script','HTML encoding','VULNERABLE']];$moduleIds=[];foreach($fixtures as $row){$insert->execute($row);$moduleIds[$row[0]]=(int)$pdo->lastInsertId();}
$suffix=bin2hex(random_bytes(5));$password='SyntheticLab!2026';$insertUser=$pdo->prepare('INSERT INTO users(name,email,password_hash,role,is_active) VALUES(?,?,?,?,1)');$accounts=[];foreach(['user','admin','security_admin']as $role){$email="phase7-{$role}-{$suffix}@e2e.chimera.test";$insertUser->execute(['Phase7 '.$role,$email,password_hash($password,PASSWORD_DEFAULT),$role]);$accounts[$role]=$email;}
[$disabledBase,$disabledServer]=p7Start($root,false,$servers);$disabled=p7Client();$clients[]=$disabled;$check(p7Request($disabled,$disabledBase,'GET','/lab')['status']===404&&p7Request($disabled,$disabledBase,'GET','/lab/sqli?q=ARC-001')['status']===404&&p7Request($disabled,$disabledBase,'GET','/lab/robots.txt')['status']===404,'Global default-off switch makes every lab route a safe 404');
$disabledSecurity=p7Client();$clients[]=$disabledSecurity;p7Login($disabledSecurity,$disabledBase,$accounts['security_admin'],$password);$disabledDashboard=p7Request($disabledSecurity,$disabledBase,'GET','/security/lab');$check($disabledDashboard['status']===200&&str_contains($disabledDashboard['body'],'LAB STATUS: DISABLED'),'Security Admin sees disabled status without an HTTP enable control');$check(!str_contains($disabledDashboard['body'],'Open lab registry')&&!str_contains($disabledDashboard['body'],'Open BOLA / IDOR exercise'),'Disabled lab management does not offer exercise links');p7Stop($disabledServer);array_pop($servers);
[$base,$enabledServer]=p7Start($root,true,$servers);$guest=p7Client();$clients[]=$guest;$index=p7Request($guest,$base,'GET','/lab');$robots=p7Request($guest,$base,'GET','/lab/robots.txt');$check($index['status']===200&&($index['headers']['x-chimera-lab']??'')==='controlled-enabled'&&str_contains($index['body'],'AUTHORIZED TRAINING ENVIRONMENT'),'Enabled lab publishes an explicit controlled banner and header');$check($robots['status']===200&&str_contains($robots['body'],'/lab/sqli')&&!str_contains($robots['body'],'DB_PASSWORD'),'Recon hint exposes only lab routes');
$exact=p7Request($guest,$base,'GET','/lab/sqli?q='.rawurlencode('ARC-001'));$injected=p7Request($guest,$base,'GET','/lab/sqli?q='.rawurlencode("' OR '1'='1"));$blocked=p7Request($guest,$base,'GET','/lab/sqli?q='.rawurlencode("' UNION SELECT password FROM users"));$check(str_contains($exact['body'],'Returned 1 synthetic record')&&str_contains($injected['body'],'Returned 3 synthetic record'),'Vulnerable SQL module demonstrates bounded unauthorized synthetic retrieval');$check(!str_contains($blocked['body'],'user@')&&!str_contains($blocked['body'],'password_hash')&&str_contains($blocked['body'],'Returned 0 synthetic record'),'SQL lab blocks cross-table syntax and exposes no real data');
$idor=p7Request($guest,$base,'GET','/lab/idor?actor=analyst-a&id=LAB-2001');$realId=p7Request($guest,$base,'GET','/lab/idor?actor=analyst-a&id=1');$check(str_contains($idor['body'],'Bluebird audit worksheet')&&str_contains($idor['body'],'analyst-b'),'Vulnerable IDOR reveals only another synthetic lab object');$check(!str_contains($realId['body'],'Bluebird')&&str_contains($realId['body'],'not found or not authorized'),'Real-style document IDs cannot enter the lab object space');
$xssPayload='<script>document.body.dataset.lab="executed"</script>';$xss=p7Request($guest,$base,'GET','/lab/xss?input='.rawurlencode($xssPayload));$csp=$xss['headers']['content-security-policy']??'';$check(str_contains($xss['body'],$xssPayload)&&str_contains($csp,'sandbox allow-scripts')&&str_contains($csp,"connect-src 'none'")&&!str_contains($csp,'allow-same-origin'),'Vulnerable reflection executes only inside an opaque-origin network-disabled sandbox');
$user=p7Client();$admin=p7Client();$security=p7Client();array_push($clients,$user,$admin,$security);p7Login($user,$base,$accounts['user'],$password);p7Login($admin,$base,$accounts['admin'],$password);p7Login($security,$base,$accounts['security_admin'],$password);$check(p7Request($user,$base,'GET','/security/lab')['status']===403&&p7Request($admin,$base,'GET','/security/lab')['status']===403,'User and Admin cannot access lab management');$dashboard=p7Request($security,$base,'GET','/security/lab');$check($dashboard['status']===200&&str_contains($dashboard['body'],'LAB STATUS: ENABLED'),'Security Admin sees enabled lab status and module registry');$check(str_contains($dashboard['body'],'Open lab registry')&&str_contains($dashboard['body'],'/lab"')&&str_contains($dashboard['body'],'/lab/idor"')&&str_contains($dashboard['body'],'/lab/sqli"')&&str_contains($dashboard['body'],'/lab/xss"'),'Enabled lab management links to registry and three controlled exercises');$missingCsrf=p7Request($security,$base,'POST','/security/lab/modules/'.$moduleIds['CHIM-VULN-002'].'/state',['state'=>'REMEDIATED']);$check($missingCsrf['status']===419,'Lab state mutation requires CSRF');
foreach($moduleIds as $identifier=>$id){$page=p7Request($security,$base,'GET','/security/lab');$change=p7Request($security,$base,'POST','/security/lab/modules/'.$id.'/state',['_token'=>p7Csrf($page['body']),'state'=>'REMEDIATED']);$check($change['status']===302,"Security Admin changes {$identifier} to REMEDIATED with POST and CSRF");}
$retestSql=p7Request($guest,$base,'GET','/lab/sqli?q='.rawurlencode("' OR '1'='1"));$retestIdor=p7Request($guest,$base,'GET','/lab/idor?actor=analyst-a&id=LAB-2001');$retestXss=p7Request($guest,$base,'GET','/lab/xss?input='.rawurlencode($xssPayload));$encodedXss=htmlspecialchars($xssPayload,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');$check(str_contains($retestSql['body'],'Returned 0 synthetic record'),'SQLi countermeasure prevents the same predicate-bypass retest');$check(str_contains($retestIdor['body'],'not found or not authorized')&&!str_contains($retestIdor['body'],'Bluebird'),'IDOR countermeasure enforces synthetic ownership on retest');$check(!str_contains($retestXss['body'],$xssPayload)&&str_contains($retestXss['body'],$encodedXss),'XSS countermeasure encodes the same reflected payload on retest');
$labEvents=$pdo->query("SELECT event_type,security_session_id,risk_delta,metadata_json FROM security_events WHERE id>{$eventStart} AND event_type LIKE 'LAB_%'")->fetchAll();$types=array_column($labEvents,'event_type');$isolated=array_reduce($labEvents,static fn(bool $ok,array $row):bool=>$ok&&$row['security_session_id']===null&&(int)$row['risk_delta']===0,true);$check(in_array('LAB_VULNERABILITY_INTERACTION',$types,true)&&in_array('LAB_REMEDIATED_TEST',$types,true)&&in_array('LAB_MODULE_STATE_CHANGED',$types,true),'Vulnerable interaction, remediated retest, and state changes are observable');$check($isolated,'All lab telemetry remains zero-score and outside operational security sessions');
$payload=(string)$pdo->query("SELECT GROUP_CONCAT(metadata_json SEPARATOR '\n') FROM security_events WHERE id>{$eventStart} AND event_type LIKE 'LAB_%'")->fetchColumn();$check(!preg_match('/password|cookie|authorization|session_identifier|DB_PASSWORD|CHM_HONEY_/i',$payload),'Lab telemetry contains no secrets or payload material');$check(p7Request($user,$base,'GET','/dashboard')['status']===200&&p7Request($security,$base,'GET','/security')['status']===200&&p7Request($security,$base,'GET','/admin')['status']===403,'Real authentication and strict role separation remain unchanged');
echo"\n{$passes} Phase 7 HTTP E2E checks passed, {$failures} failed.\n";
}catch(Throwable $e){$failures++;echo'[FAIL] Phase 7 HTTP E2E exception: '.$e->getMessage()."\n";}finally{foreach($clients as $client)if($client instanceof CurlHandle)curl_close($client);foreach($servers as $server)p7Stop($server);$pdo->exec("DELETE FROM security_events WHERE id>{$eventStart}");$pdo->exec("DELETE FROM security_sessions WHERE id>{$sessionStart}");$pdo->exec("DELETE FROM vulnerability_modules WHERE id>{$moduleStart}");$pdo->exec("DELETE FROM users WHERE id>{$userStart}");}
exit($failures===0?0:1);
