<?php
declare(strict_types=1);
use App\Core\Env;
$root=dirname(__DIR__);require $root.'/app/Core/Env.php';Env::load($root.'/.env');
if((string)getenv('TEST_DB_DATABASE')!=='chimera_test'||(string)getenv('DB_DATABASE')!=='chimera'||(string)getenv('DB_PORT')!=='3308'){echo"[FAIL] Phase 8 HTTP database guards failed.\n";exit(1);}
$testUser=(string)getenv('TEST_DB_USERNAME');$testPassword=(string)getenv('TEST_DB_PASSWORD');if($testUser===''||$testPassword===''){echo"[FAIL] Dedicated test credentials are required.\n";exit(1);}
$pdo=new PDO('mysql:host=127.0.0.1;port=3308;dbname=chimera_test;charset=utf8mb4',$testUser,$testPassword,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);$conn=$pdo->query('SELECT DATABASE() db,@@port port,CURRENT_USER() usr')->fetch();if($conn['db']!=='chimera_test'||(int)$conn['port']!==3308||!str_starts_with($conn['usr'],'chimera_test_app@')){echo"[FAIL] Unsafe Phase 8 HTTP target.\n";exit(1);}
$tables=['security_events','security_sessions','users','decoy_endpoints','honeytokens','honeytoken_events','vulnerability_modules','vulnerability_state_changes'];$start=[];foreach($tables as$t)$start[$t]=(int)$pdo->query("SELECT COALESCE(MAX(id),0) FROM {$t}")->fetchColumn();$p=0;$f=0;$servers=[];$clients=[];$check=function(bool$ok,string$label)use(&$p,&$f):void{echo($ok?'[PASS] ':'[FAIL] ').$label.PHP_EOL;$ok?$p++:$f++;};
function p8Client():CurlHandle{$c=curl_init();curl_setopt_array($c,[CURLOPT_COOKIEFILE=>'',CURLOPT_RETURNTRANSFER=>true,CURLOPT_HEADER=>true,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_TIMEOUT=>10]);return$c;}
function p8Req(CurlHandle$c,string$base,string$method,string$path,?array$fields=null):array{curl_setopt($c,CURLOPT_URL,$base.$path);curl_setopt($c,CURLOPT_CUSTOMREQUEST,$method);if($method==='GET'){curl_setopt($c,CURLOPT_HTTPGET,true);curl_setopt($c,CURLOPT_POSTFIELDS,null);}else{curl_setopt($c,CURLOPT_POST,true);curl_setopt($c,CURLOPT_POSTFIELDS,http_build_query($fields??[]));}$raw=curl_exec($c);if(!is_string($raw))throw new RuntimeException(curl_error($c));$size=curl_getinfo($c,CURLINFO_HEADER_SIZE);$head=substr($raw,0,$size);$headers=[];foreach(preg_split('/\r\n|\n|\r/',trim($head))as$line)if(str_contains($line,':')){[$k,$v]=explode(':',$line,2);$headers[strtolower(trim($k))]=trim($v);}return['status'=>(int)curl_getinfo($c,CURLINFO_RESPONSE_CODE),'headers'=>$headers,'body'=>substr($raw,$size)];}
function p8Csrf(string$html):string{if(!preg_match('/name="_token"\s+value="([^"]+)"/',$html,$m))throw new RuntimeException('CSRF token missing.');return html_entity_decode($m[1],ENT_QUOTES|ENT_HTML5,'UTF-8');}
function p8Login(CurlHandle$c,string$base,string$email,string$password):array{$page=p8Req($c,$base,'GET','/login');return p8Req($c,$base,'POST','/login',['_token'=>p8Csrf($page['body']),'email'=>$email,'password'=>$password]);}
function p8Start(string$root,array&$servers):string{$sock=stream_socket_server('tcp://127.0.0.1:0',$errno,$error);if(!is_resource($sock))throw new RuntimeException('Port allocation failed.');$name=stream_socket_get_name($sock,false);fclose($sock);$port=(int)substr(strrchr((string)$name,':'),1);$base='http://127.0.0.1:'.$port;$env=getenv();$env['CHIMERA_E2E_BASE_URL']=$base;$env['CHIMERA_E2E_STORAGE']=$root.'/storage/uploads/e2e-documents';$env['VULNERABILITY_LAB_ENABLED']='true';$proc=proc_open([PHP_BINARY,'-S','127.0.0.1:'.$port,'-t',$root.'/public',$root.'/tests/e2e_server_router.php'],[0=>['pipe','r'],1=>['file',$root.'/storage/logs/phase8-e2e-server.log','a'],2=>['file',$root.'/storage/logs/phase8-e2e-server.log','a']],$pipes,$root,$env);if(!is_resource($proc))throw new RuntimeException('Server start failed.');fclose($pipes[0]);$servers[]=$proc;for($i=0;$i<30;$i++){try{$probe=p8Client();$ready=p8Req($probe,$base,'GET','/')['status']===200;curl_close($probe);if($ready)return$base;}catch(Throwable){}usleep(100000);}throw new RuntimeException('Server readiness failed.');}
try{
 $suffix=bin2hex(random_bytes(4));$password='Phase8-E2E!2026';$userStmt=$pdo->prepare('INSERT INTO users(name,email,password_hash,role,is_active)VALUES(?,?,?,?,1)');$accounts=[];foreach(['user','admin','security_admin']as$role){$email="phase8-{$role}-{$suffix}@e2e.chimera.test";$userStmt->execute(['Phase8 '.$role,$email,password_hash($password,PASSWORD_DEFAULT),$role]);$accounts[$role]=$email;}
 $pdo->exec("INSERT INTO decoy_endpoints(decoy_identifier,path,name,type,is_active,response_mode)VALUES('DEC-P8-E2E','/api/debug','Synthetic debug','DEBUG_API',1,'SYNTHETIC_JSON')");$material='CHM_HONEY_HT_API_001';$token=$pdo->prepare("INSERT INTO honeytokens(token_identifier,description,token_hash,is_active)VALUES('HT-API-001','Synthetic Phase 8 token',?,1)");$token->execute([hash('sha256',$material)]);
 $module=$pdo->prepare('INSERT INTO vulnerability_modules(vulnerability_identifier,name,description,affected_component,expected_attack_surface,learning_objective,expected_impact,mitigation,state,is_active)VALUES(?,?,?,?,?,?,?,?,?,1)');$module->execute(['CHIM-VULN-002','Controlled SQL Injection','Synthetic dataset','SQL Injection','/lab/sqli','Compare modes','Synthetic rows only','Prepared parameters','VULNERABLE']);$moduleId=(int)$pdo->lastInsertId();
 $base=p8Start($root,$servers);$guest=p8Client();$user=p8Client();$admin=p8Client();$security=p8Client();array_push($clients,$guest,$user,$admin,$security);
 $guestApi=p8Req($guest,$base,'GET','/api/security/analytics/summary');$check($guestApi['status']===401,'Guest analytics API request returns 401');
 $decoy=p8Req($guest,$base,'GET','/api/debug');$honey=p8Req($guest,$base,'GET','/api/debug/verify?token='.$material);$check($decoy['status']===200&&str_contains($decoy['body'],'chimera-debug-proxy'),'Operational flow records a genuine synthetic decoy interaction');$check($honey['status']===410,'Operational flow records a genuine synthetic honeytoken trigger');
 p8Login($user,$base,$accounts['user'],$password);p8Login($admin,$base,$accounts['admin'],$password);p8Login($security,$base,$accounts['security_admin'],$password);
 $check(p8Req($user,$base,'GET','/api/security/analytics/summary')['status']===403&&p8Req($admin,$base,'GET','/api/security/analytics/summary')['status']===403,'USER and ADMIN cannot access analytics API');
 $dashboard=p8Req($security,$base,'GET','/security/analytics');$check($dashboard['status']===200&&str_contains($dashboard['body'],'Security analytics'),'Security Admin can open analytics dashboard');$check(str_contains($dashboard['body'],'/api/security/analytics/export?type=session_evidence&amp;format=json'),'Dashboard emits the exact generic session evidence export contract');
 $vuln=p8Req($guest,$base,'GET','/lab/sqli?q='.rawurlencode("' OR '1'='1"));$check(str_contains($vuln['body'],'Returned 3 synthetic record'),'LAB flow records vulnerable synthetic observation');
 $labPage=p8Req($security,$base,'GET','/security/lab');$changed=p8Req($security,$base,'POST','/security/lab/modules/'.$moduleId.'/state',['_token'=>p8Csrf($labPage['body']),'state'=>'REMEDIATED']);$remediated=p8Req($guest,$base,'GET','/lab/sqli?q='.rawurlencode("' OR '1'='1"));$check($changed['status']===302&&str_contains($remediated['body'],'Returned 0 synthetic record'),'Same controlled LAB test is prevented after remediation');
 $summary=p8Req($security,$base,'GET','/api/security/analytics/summary');$json=json_decode($summary['body'],true);$check($summary['status']===200&&($json['data']['deception']['decoy_interactions']??0)>=1&&($json['data']['deception']['honeytoken_triggers']??0)>=1,'Analytics summary measures generated deception evidence');
 $sqlModules=array_values(array_filter($json['data']['lab']['modules']??[],static fn(array$m):bool=>$m['module_identifier']==='CHIM-VULN-002'));$check($sqlModules!==[]&&$sqlModules[0]['vulnerable_tests']>=1&&$sqlModules[0]['remediated_tests']>=1,'LAB analytics compares vulnerable and remediated evidence');
 $sessionId=(int)$pdo->query("SELECT id FROM security_sessions WHERE id>{$start['security_sessions']} AND user_id IS NULL ORDER BY threat_score DESC,id LIMIT 1")->fetchColumn();$session=p8Req($security,$base,'GET','/api/security/analytics/sessions/'.$sessionId);$sessionJson=json_decode($session['body'],true);$check($session['status']===200&&($sessionJson['data']['assessment']['integrity_status']??'')==='CONSISTENT','Session API reconstructs score integrity');
 $check(array_key_exists('detection_latency_seconds',$sessionJson['data']['detection']??[])&&array_key_exists('time_to_deception_seconds',$sessionJson['data']['detection']??[])&&array_key_exists('time_to_honeytoken_seconds',$sessionJson['data']['detection']??[]),'Session API exposes all three documented timing measurements');
 $timeline=p8Req($security,$base,'GET','/api/security/analytics/timeline?limit=20');$timelineJson=json_decode($timeline['body'],true);$domains=array_unique(array_column($timelineJson['data']??[],'domain'));$check($timeline['status']===200&&in_array('OPERATIONAL_SECURITY',$domains,true)&&in_array('CONTROLLED_LAB',$domains,true),'Unified timeline distinguishes operational and controlled-LAB evidence');
 $jsonExport=p8Req($security,$base,'GET','/api/security/analytics/export?type=session_evidence&format=json&session_id='.$sessionId);$check($jsonExport['status']===200&&str_contains($jsonExport['headers']['content-type']??'','application/json')&&json_decode($jsonExport['body'],true)!==null,'Authorized JSON evidence export succeeds');
 $genericSessionPath='/api/security/analytics/export?type=session_evidence&format=json';
 $genericGuest=p8Req($guest,$base,'GET',$genericSessionPath);$genericUser=p8Req($user,$base,'GET',$genericSessionPath);$genericAdmin=p8Req($admin,$base,'GET',$genericSessionPath);$genericSecurity=p8Req($security,$base,'GET',$genericSessionPath);$genericJson=json_decode($genericSecurity['body'],true);
 $check($genericGuest['status']===401,'Guest is denied the exact UI-generated session evidence export');
 $check($genericUser['status']===403&&$genericAdmin['status']===403,'USER and ADMIN are denied the exact UI-generated session evidence export');
 $check($genericSecurity['status']===200&&str_contains($genericSecurity['headers']['content-type']??'','application/json')&&is_array($genericJson),'Security Admin exact UI-generated session evidence export succeeds');
 $genericBody=$genericSecurity['body'];$latestSourceHash=(string)$pdo->query('SELECT source_hash FROM security_sessions ORDER BY last_seen_at DESC,id DESC LIMIT 1')->fetchColumn();$check(!preg_match('/source_ip|source_safe_identifier|source_identifier|source_hash|password_hash|token_hash|session_identifier|authorization_header|csrf_token|cookie|credential|DB_PASSWORD/i',$genericBody)&&($latestSourceHash===''||!str_contains($genericBody,$latestSourceHash)),'Generic session evidence export omits source, credential, and session-secret fields');
 $unsupportedExport=p8Req($security,$base,'GET','/api/security/analytics/export?type=not_supported&format=json');$unsupportedJson=json_decode($unsupportedExport['body'],true);$check($unsupportedExport['status']===422&&($unsupportedJson['error']['code']??'')==='INVALID_EXPORT','Unsupported export types still return INVALID_EXPORT');
 $incompatibleExport=p8Req($security,$base,'GET',$genericSessionPath.'&event_type=LOGIN_FAILURE');$incompatibleJson=json_decode($incompatibleExport['body'],true);$check($incompatibleExport['status']===422&&($incompatibleJson['error']['code']??'')==='INVALID_FILTER','Incompatible session evidence filters still fail closed');
 $csvExport=p8Req($security,$base,'GET','/api/security/analytics/export?type=security_events&format=csv');$check($csvExport['status']===200&&str_contains($csvExport['headers']['content-type']??'','text/csv')&&str_contains($csvExport['body'],'evidence_id'),'Authorized CSV evidence export succeeds');
 $payload=$summary['body'].$session['body'].$jsonExport['body'].$csvExport['body'];$check(!preg_match('/password_hash|token_hash|session_identifier|DB_PASSWORD|storage_name/i',$payload),'UI/API/export evidence excludes secret implementation fields');
 $invalidFilter=p8Req($security,$base,'GET','/api/security/analytics/timeline?severity=ROOT');$invalidJson=json_decode($invalidFilter['body'],true);$check($invalidFilter['status']===422&&($invalidJson['error']['code']??'')==='INVALID_FILTER','Malformed allowlist filter fails closed with a safe 422 response');
 $scoreBefore=(int)$pdo->query("SELECT threat_score FROM security_sessions WHERE id={$sessionId}")->fetchColumn();p8Req($security,$base,'GET','/api/security/analytics/summary');$scoreAfter=(int)$pdo->query("SELECT threat_score FROM security_sessions WHERE id={$sessionId}")->fetchColumn();$check($scoreBefore===$scoreAfter,'Analytics HTTP reads do not modify threat scores');
}catch(Throwable$e){$f++;echo'[FAIL] Phase 8 HTTP E2E exception: '.$e->getMessage().PHP_EOL;}
finally{foreach($clients as$c)if($c instanceof CurlHandle)curl_close($c);foreach($servers as$server)if(is_resource($server)){proc_terminate($server);proc_close($server);}$pdo->exec("DELETE FROM vulnerability_state_changes WHERE id>{$start['vulnerability_state_changes']}");$pdo->exec("DELETE FROM honeytoken_events WHERE id>{$start['honeytoken_events']}");$pdo->exec("DELETE FROM security_events WHERE id>{$start['security_events']}");$pdo->exec("DELETE FROM security_sessions WHERE id>{$start['security_sessions']}");$pdo->exec("DELETE FROM vulnerability_modules WHERE id>{$start['vulnerability_modules']}");$pdo->exec("DELETE FROM honeytokens WHERE id>{$start['honeytokens']}");$pdo->exec("DELETE FROM decoy_endpoints WHERE id>{$start['decoy_endpoints']}");$pdo->exec("DELETE FROM users WHERE id>{$start['users']}");}
$residual=(int)$pdo->query("SELECT (SELECT COUNT(*) FROM users WHERE id>{$start['users']})+(SELECT COUNT(*) FROM security_events WHERE id>{$start['security_events']})+(SELECT COUNT(*) FROM security_sessions WHERE id>{$start['security_sessions']})+(SELECT COUNT(*) FROM decoy_endpoints WHERE id>{$start['decoy_endpoints']})+(SELECT COUNT(*) FROM honeytokens WHERE id>{$start['honeytokens']})+(SELECT COUNT(*) FROM vulnerability_modules WHERE id>{$start['vulnerability_modules']})")->fetchColumn();$check($residual===0,'Phase 8 HTTP/E2E leaves no fixture records in chimera_test');
echo"\n{$p} Phase 8 HTTP E2E checks passed, {$f} failed.\n";exit($f===0?0:1);
