<?php $a=$analytics;$f=$a['filters'];$fmt=static fn(mixed $v):string=>$v===null?'N/A':number_format((float)$v,2).' s'; ?>
<section class="soc-shell min-h-screen">
<div class="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8">
 <div class="dashboard-heading"><div><p class="section-label text-cyan-400">Evidence & evaluation</p><h1 class="text-4xl font-semibold tracking-tight text-slate-100">Security analytics</h1><p class="mt-3 max-w-3xl text-slate-400">Read-only measurements from persisted operational, deception, adaptive, and controlled-lab evidence.</p></div><a class="button button-secondary" href="<?=e(url('/security'))?>">Telemetry</a></div>
 <?php if($f['errors']!==[]):?><div class="alert alert-error mt-6" role="alert"><?=e(implode(' ',$f['errors']))?></div><?php endif;?>
 <form class="mt-8 grid gap-3 rounded-2xl border border-slate-800 bg-slate-900 p-5 md:grid-cols-4" method="get" action="<?=e(url('/security/analytics'))?>">
  <label class="text-sm text-slate-300">From<input class="field mt-2" type="date" name="date_from" value="<?=e($f['date_from'])?>"></label><label class="text-sm text-slate-300">To<input class="field mt-2" type="date" name="date_to" value="<?=e($f['date_to'])?>"></label>
  <label class="text-sm text-slate-300">Category<select class="field mt-2" name="category"><option value="">All</option><?php foreach($categories as $v):?><option <?=$f['category']===$v?'selected':''?>><?=e($v)?></option><?php endforeach;?></select></label>
  <label class="text-sm text-slate-300">Event type<select class="field mt-2" name="type"><option value="">All</option><?php foreach($eventTypes as $v):?><option <?=$f['type']===$v?'selected':''?>><?=e($v)?></option><?php endforeach;?></select></label>
  <label class="text-sm text-slate-300">Severity<select class="field mt-2" name="severity"><option value="">All</option><?php foreach($severities as $v):?><option <?=$f['severity']===$v?'selected':''?>><?=e($v)?></option><?php endforeach;?></select></label>
  <label class="text-sm text-slate-300">Threat level<select class="field mt-2" name="threat_level"><option value="">All</option><?php foreach(['LOW','MEDIUM','HIGH','CRITICAL'] as $v):?><option <?=$f['threat_level']===$v?'selected':''?>><?=e($v)?></option><?php endforeach;?></select></label>
  <label class="text-sm text-slate-300">Adaptive profile<select class="field mt-2" name="profile"><option value="">All</option><?php foreach(['LOW','MEDIUM','HIGH','CRITICAL'] as $v):?><option <?=$f['profile']===$v?'selected':''?>><?=e($v)?></option><?php endforeach;?></select></label>
  <label class="text-sm text-slate-300">Lab module<select class="field mt-2" name="module"><option value="">All</option><?php foreach(['CHIM-VULN-001','CHIM-VULN-002','CHIM-VULN-003'] as $v):?><option <?=$f['module']===$v?'selected':''?>><?=e($v)?></option><?php endforeach;?></select></label>
  <div class="flex gap-3 md:col-span-4"><button class="button button-primary">Apply</button><a class="button button-secondary" href="<?=e(url('/security/analytics'))?>">Clear</a></div>
 </form>
 <div class="mt-8 grid gap-px overflow-hidden rounded-2xl border border-slate-800 bg-slate-800 sm:grid-cols-2 lg:grid-cols-6"><?php foreach([['Security events',$a['events']['total']],['Operational sessions',$a['sessions']['total']],['High / critical',$a['sessions']['by_level']['HIGH']+$a['sessions']['by_level']['CRITICAL']],['Decoy interactions',$a['deception']['decoy_interactions']],['Honeytokens',$a['deception']['honeytoken_triggers']],['Controlled lab',$a['events']['lab_total']]] as[$l,$v]):?><div class="bg-slate-900 p-5"><span class="text-xs uppercase tracking-wide text-slate-500"><?=e($l)?></span><strong class="mt-2 block text-3xl text-slate-100"><?=e((string)$v)?></strong></div><?php endforeach;?></div>
 <div class="mt-8 grid gap-6 lg:grid-cols-2">
  <section class="rounded-2xl border border-slate-800 bg-slate-900 p-6"><h2 class="text-lg font-semibold">Threat assessment</h2><div class="mt-5 grid grid-cols-4 gap-3"><?php foreach($a['sessions']['by_level'] as$l=>$v):?><div class="rounded-xl bg-slate-950 p-3 text-center"><span class="text-xs text-slate-500"><?=e($l)?></span><strong class="block text-xl"><?=e((string)$v)?></strong></div><?php endforeach;?></div><p class="mt-5 text-sm text-slate-400">Score avg <?=e((string)($a['sessions']['average_score']??'N/A'))?> · median <?=e((string)($a['sessions']['median_score']??'N/A'))?> · range <?=e((string)($a['sessions']['minimum_score']??'N/A'))?>–<?=e((string)($a['sessions']['maximum_score']??'N/A'))?></p><h3 class="mt-6 text-sm font-semibold text-slate-200">Top contributors</h3><?php foreach(array_slice($a['sessions']['contributors'],0,8) as$r):?><div class="mt-2 flex justify-between text-sm text-slate-400"><span><?=e($r['label'])?></span><span><?=e((string)$r['total'])?> events / <?=e((string)$r['points'])?> pts</span></div><?php endforeach;?></section>
  <section class="rounded-2xl border border-slate-800 bg-slate-900 p-6"><h2 class="text-lg font-semibold">Detection performance</h2><?php foreach(['detection_latency'=>'Detection latency','time_to_deception'=>'Time to deception','time_to_honeytoken'=>'Time to honeytoken'] as$k=>$l):$m=$a['detection'][$k];?><div class="mt-5 border-b border-slate-800 pb-4"><div class="flex justify-between"><span class="text-slate-300"><?=e($l)?></span><strong><?=e($fmt($m['average_seconds']))?></strong></div><p class="mt-1 text-xs text-slate-500"><?=e((string)$m['measurable_sessions'])?> measurable · min <?=e($fmt($m['minimum_seconds']))?> · max <?=e($fmt($m['maximum_seconds']))?></p></div><?php endforeach;?></section>
  <section class="rounded-2xl border border-slate-800 bg-slate-900 p-6"><h2 class="text-lg font-semibold">Deception & adaptive profiles</h2><dl class="mt-5 grid grid-cols-2 gap-4 text-sm"><div><dt class="text-slate-500">Profile selections</dt><dd class="text-2xl"><?=e((string)$a['deception']['profile_selections'])?></dd></div><div><dt class="text-slate-500">Transitions</dt><dd class="text-2xl"><?=e((string)$a['deception']['profile_transitions'])?></dd></div><div><dt class="text-slate-500">Adaptive renders</dt><dd class="text-2xl"><?=e((string)$a['deception']['adaptive_renders'])?></dd></div><div><dt class="text-slate-500">Sessions with interaction</dt><dd class="text-2xl"><?=e((string)$a['deception']['sessions_with_deception'])?></dd></div></dl><?php foreach($a['deception']['interactions_by_profile'] as$r):?><div class="mt-3 flex justify-between text-sm text-slate-400"><span><?=e($r['label'])?></span><strong><?=e((string)$r['total'])?></strong></div><?php endforeach;?></section>
  <section class="rounded-2xl border border-slate-800 bg-slate-900 p-6"><h2 class="text-lg font-semibold">Controlled lab evaluation</h2><p class="mt-1 text-xs text-amber-400">Authorized lab evidence is excluded from operational scoring.</p><?php foreach($a['lab']['modules'] as$m):?><div class="mt-4 rounded-xl bg-slate-950 p-4"><div class="flex justify-between"><strong><?=e($m['module_identifier'])?></strong><span class="text-xs text-slate-400"><?=e($m['current_state'])?></span></div><p class="mt-2 text-sm text-slate-400"><?=e((string)$m['vulnerable_tests'])?> vulnerable tests · <?=e((string)$m['remediated_tests'])?> remediated retests</p></div><?php endforeach;?></section>
 </div>
 <section class="mt-8 rounded-2xl border border-slate-800 bg-slate-900 p-6"><h2 class="text-lg font-semibold">Evidence export</h2><p class="mt-1 text-sm text-slate-400">Security Admin only, bounded to 1,000 records with data minimization. Applicable active filters are preserved.</p><div class="mt-4 flex flex-wrap gap-2"><?php foreach($exportTypes as$t):?><a class="button button-secondary" href="<?=e($exportUrls[$t])?>"><?=e($t)?> JSON</a><?php endforeach;?></div></section>
 <section class="mt-8 overflow-hidden rounded-2xl border border-slate-800 bg-slate-900"><div class="border-b border-slate-800 px-6 py-5"><h2 class="text-lg font-semibold">Operational security sessions</h2><p class="mt-1 text-sm text-slate-400">Newest 25 matching sessions with explainable evidence.</p></div><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-slate-950 text-slate-400"><tr><th class="px-5 py-3">Session</th><th class="px-5 py-3">Level</th><th class="px-5 py-3">Score</th><th class="px-5 py-3">Contributors</th><th class="px-5 py-3">Last activity</th></tr></thead><tbody class="divide-y divide-slate-800"><?php foreach($a['session_list'] as$row):?><tr><td class="px-5 py-3"><a class="text-emerald-400" href="<?=e(url('/security/analytics/sessions/'.$row['internal_id']))?>"><?=e($row['evidence_id'])?></a><span class="ml-2 text-xs text-slate-500"><?=e($row['lifecycle_status'])?></span></td><td class="px-5 py-3"><?=e($row['classification'])?></td><td class="px-5 py-3"><?=e((string)$row['threat_score'])?></td><td class="px-5 py-3"><?=e((string)$row['contributor_count'])?></td><td class="px-5 py-3 text-slate-400"><?=e($row['last_seen_at'])?></td></tr><?php endforeach;?></tbody></table></div></section>
 <section class="mt-8 overflow-hidden rounded-2xl border border-slate-800 bg-slate-900"><div class="border-b border-slate-800 px-6 py-5"><h2 class="text-lg font-semibold">Unified recent timeline</h2></div><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-slate-950 text-slate-400"><tr><th class="px-5 py-3">Time</th><th class="px-5 py-3">Evidence</th><th class="px-5 py-3">Domain</th><th class="px-5 py-3">Event</th><th class="px-5 py-3">Contribution</th></tr></thead><tbody class="divide-y divide-slate-800"><?php foreach($a['timeline'] as$row):?><tr><td class="px-5 py-3 text-slate-400"><?=e($row['created_at'])?></td><td class="px-5 py-3 font-mono text-xs"><?=e($row['evidence_id'])?></td><td class="px-5 py-3 text-xs <?= $row['domain']==='CONTROLLED_LAB'?'text-amber-400':'text-cyan-400'?>"><?=e($row['domain'])?></td><td class="px-5 py-3"><?=e($row['event_type'])?><?php if($row['security_session_evidence_id']):?><a class="ml-2 text-emerald-400" href="<?=e(url('/security/analytics/sessions/'.(int)substr($row['security_session_evidence_id'],4)))?>">session</a><?php endif;?></td><td class="px-5 py-3"><?=e((string)array_sum(array_column($row['contributors'],'risk_delta')))?></td></tr><?php endforeach;?></tbody></table></div></section>
</div></section>
